### ISSUE TITLE
ddev-webserver container build fails because of unavailable packages.blackfire.io debian repo

### ISSUE THREAD

**Issue by syssi** [ddev/ddev#5620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
```
</details>         

Skipped.

### Expected Behavior

Successful container build. `ddev start` returns `0`.

### Actual Behavior

```
#13 [web 4/6] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests webp
#13 2.896 E: Failed to fetch http://packages.blackfire.io/debian/dists/any/InRelease  403  Forbidden [IP: 3.5.66.150 80]
#13 2.896 E: The repository 'http://packages.blackfire.io/debian any InRelease' is not signed.
#13 ERROR: process "/bin/bash -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests webp" did not complete successfully: exit code: 100
------
 > [web 4/6] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests webp:
2.896 E: Failed to fetch http://packages.blackfire.io/debian/dists/any/InRelease  403  Forbidden [IP: 3.5.66.150 80]
2.896 E: The repository 'http://packages.blackfire.io/debian any InRelease' is not signed.
------
```

### Steps To Reproduce

```
ddev config --docroot=. --project-type=php --webimage-extra-packages webp && ddev start
```

### Anything else?

Is there a workaround to get rid of blackfire.io temporary? We are dependent on the custom container build but we don't need blackfire.io usually.

**Comment by mattvb91** [comment]
same issue here. Cant even downgrade either because other versions broken too with ` ComposeCmd failed to run` issues. Completely broken now across multiple versions.

**Comment by nostadt** [comment]
Would love to be able to disable blackfire when not needed, or actually have it disabled by default and enable if needed. Given the price of blackfire, I assume many people don't use this.

**Comment by pbowyer** [comment]
Seems to be resolved for me. Approx 1.25h after I first encountered it. Thanks Blackfire team for sorting the outage!

**Comment by fabianderijk** [comment]
It worked for me as well. Until I started another project.....

**Comment by rfay** [comment]
Could you please see if changing to nodejs_version: 18 is a workaround?

**Comment by fabianderijk** [comment]
> Could you please see if changing to nodejs_version: 18 is a workaround?

That doesn't work for me

**Comment by pbowyer** [comment]
@rfay Commenting out `webimage_extra_packages: [php7.4-imap]` fixed it for me

**Comment by rfay** [comment]
That was the other thing I was going to suggest, thx

**Comment by matthiaz** [comment]
Hi

There was an issue with blackfire packagecloud, a fix has been rolled out this should be resolved within a few minutes.

**Comment by rfay** [comment]
The blackfire people say this is being worked on and should be solved soon, like a few minutes.

**Comment by matthiaz** [comment]
Hi all, 

I've just confirmed that the fix has been rolled out, and is working. 
Please try again. Feel free to post back if you are still having issues. I'm monitoring this thread for the time being.

Matthias
Blackfire/PlatformSh team

**Comment by syssi** [comment]
It's working reliable again:

```
# proof
ddev stop; rm -rf .ddev; ddev config --docroot=. --project-type=php --webimage-extra-packages webp --nodejs-version 18 && ddev start; echo $?
```

**Comment by iainsaxon** [comment]
Sorry to post on a closed comment but it seemed more correct than creating up a new ticket when all the context and discussion is already here.

This has become an issue again when I `ddev start` or `ddev d refresh` a project:
```
1.674 Get:18 http://nginx.org/packages/debian bookworm/nginx arm64 Packages [7973 B]
1.811 Err:19 http://packages.blackfire.io/debian any InRelease
1.811   402  Payment Required [IP: 79.125.77.192 80]
2.089 Get:20 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease [123 kB]
```

**Comment by tyler36** [comment]
@iainsaxon 
This seems like a different error "payment required" as opposed to "403 forbidden". Wether this is simple an "friendly error" or a different problem is still undetermined. 

I opened #6235 to track this so please add additional information over there.
