### ISSUE TITLE
DDEV v1.24: Fix pre.Dockerfile handling for older PHP version installations

### ISSUE THREAD

**Issue by TerrorSquad** [ddev/ddev#6808]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

There is no summary. 

</details>

### Expected Behavior

Installing older PHP versions (7.2, 7.3, 7.4) should work, with the provided `pre.Dockerfile`.

`.ddev/web-build/pre.Dockerfile`

```Dockerfile
COPY certificates/* /usr/local/share/ca-certificates
RUN update-ca-certificates
```

### Actual Behavior

Installing older php versions is impossible because the container cannot fetch the latest package info from `https://packages.sury.org/php/dists/bookwork/InRelease` because of the missing SSL certificates.

The generated `.ddev/.webimageBuild/Dockerfile` should be changed so that the code injected from the `pre.Dockerfile` comes before installing PHP.

The older version 1.23.5 works fine. This issue is most likely the result of the new image trimming.

### Steps To Reproduce

1. Be in an environment that requires additional SSL certificates - e.g. Zscaler
2. Set up a project using older PHP version e.g. 7.2
3. Add a custom `pre.Dockerfile` that installs ZScaler certificate
4. Run `ddev start`

### Anything else?

I am posting this from my personal laptop, but I am experiencing this issue on my company's laptop. On the company's laptop, I can only use the Enterprise Github account (which doesn't allow posting here) and not my own, which is the reason for the missing debug info above.

**Comment by rfay** [comment]
Thanks for studying this carefully. Please update the title to reflect your actual situation, which is pretty "special". 

A PR is welcome.

**Comment by TerrorSquad** [comment]
You're welcome. I'll try to come up with a PR for this issue.

I've changed the title. Hopefully it's clearer now. If not, please suggest a new one.

**Comment by rfay** [comment]
This was fixed by
* https://github.com/ddev/ddev/pull/6809

Thanks!

**Comment by TerrorSquad** [comment]
Hi @rfay 

Do you think this could be deployed as a hotfix?

**Comment by rfay** [comment]
Hi @TerrorSquad - I think we'll do a point release soon, probably this week. This issue and one other rare thing were affected in v1.24.0.

I'm sure you know you can easily use HEAD, https://ddev.readthedocs.io/en/stable/developers/building-contributing/#testing-latest-commits-on-head

**Comment by TerrorSquad** [comment]
Thanks @rfay, I will checkout the new version using HEAD.

**Comment by matthieu2607** [comment]
Hi @rfay,

We are still experiencing the problem with version 1.24.1. Versions below 8.1 are no longer supported.

We are running Ubuntu 22.04 and 24.04

![Image](https://github.com/user-attachments/assets/20584441-43a2-4c59-855c-ad13cafe76ce)

Best regards

**Comment by stasadev** [comment]
@matthieu2607, see

- #6835

**Comment by matthieu2607** [comment]
@stasadev thank you ;) it works

**Comment by rfay** [comment]
@matthieu2607 it seems your question here is unrelated, but would you mind saying a little about what you use php8.0 to do in this context ?  (In the future, please open a new issue with an different question, or join us in Discord to discuss, https://ddev.com/s/discord )
